title: SEEDS Capital
url: https://seedscapital.sg
favicon: /images/scfavicon.ico
colors:
  primary-color: "#8eba58"
  secondary-color: "#43493a"
  media-colors:
    - title: media-color-one
      color: "#a7ae9c"
    - title: media-color-two
      color: "#008dac"
    - title: media-color-three
      color: "#005b8f"
    - title: media-color-four
      color: "#005b8f"
    - title: media-color-five
      color: "#005b8f"
resources_name: Resources
description: Catalysing smart monies into Singapore-based, early-stage technology startups.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://enterprisesg-seeds-staging.netlify.app
prod: https://enterprisesg-seeds-prod.netlify.app
google_analytics: "312673821"
is_government: true
shareicon: /images/isomer-logo.svg
facebook-pixel: ""
linkedin-insights: ""
